
/* <Your name here> */
/* HW1 Submission */

/* Remember to save this template file as HW1_YourNetID.sas */

/* This ODS statement followed by the one at the end of the file
   will put all of the output generated by the code in between
   into a single PDF file. That is your report for HW1. */
ods pdf file='C:\440\hw1\HW1_YourNetID.pdf' ;


/* Exercise 1 */

* Your code here;



/* Exercise 2 */

* Your code here;



/* Exercise 3 */

* Your code here;



ods pdf close;
