
/* <Your name here> */
/* HW3 Submission */

/* Remember to save this template file as HW3_YourNetID.sas */

/* This ODS statement followed by the one at the end of the file
   will put all of the output generated by the code in between
   into a single RTF file.  
   Once the results have been sent to the .rtf file, you may open 
   it in Word and include your own responses in the relevant areas
   (as directed in the exercises). That is your report for HW3. */

ods rtf file='C:\440\hw3\HW3_YourNetID.rtf' ;


/* Exercise 1 */

* Your code here;



/* Exercise 2 */

* Your code here;



/* Exercise 3 */

* Your code here;



ods rtf close;
